export const codeLanguages = [
  ['Pascal', 'Pascal'],
  ['JavaScript', 'JavaScript'],
  ['TypeScript', 'TypeScript'],
  ['Python', 'Python'],
  ['TSX', 'TSX'],
  ['JSX', 'JSX'],
  ['Vue', 'Vue'],
  ['Go', 'Go'],
  ['C', 'C'],
  ['C++', 'C++'],
  ['Java', 'Java'],
  ['C#', 'C#'],
  ['Visual Basic .NET', 'Visual Basic .NET'],
  ['SQL', 'SQL'],
  ['Assembly Language', 'Assembly Language'],
  ['PHP', 'PHP'],
  ['Ruby', 'Ruby'],
  ['Swift', 'Swift'],
  ['SwiftUI', 'SwiftUI'],
  ['Kotlin', 'Kotlin'],
  ['R', 'R'],
  ['Objective-C', 'Objective-C'],
  ['Perl', 'Perl'],
  ['SAS', 'SAS'],
  ['Scala', 'Scala'],
  ['Dart', 'Dart'],
  ['Rust', 'Rust'],
  ['Haskell', 'Haskell'],
  ['Lua', 'Lua'],
  ['Groovy', 'Groovy'],
  ['Elixir', 'Elixir'],
  ['Clojure', 'Clojure'],
  ['Lisp', 'Lisp'],
  ['Julia', 'Julia'],
  ['Matlab', 'Matlab'],
  ['Fortran', 'Fortran'],
  ['COBOL', 'COBOL'],
  ['Bash', 'Bash'],
  ['Powershell', 'Powershell'],
  ['PL/SQL', 'PL/SQL'],
  ['CSS', 'CSS'],
  ['Racket', 'Racket'],
  ['HTML', 'HTML'],
  ['NoSQL', 'NoSQL'],
  ['Natural Language', 'Natural Language'],
  ['CoffeeScript', 'CoffeeScript'],
]

export const textLanguages = [
  ['auto', 'Auto Detect'],
  ['en', 'English'],
  ['zh-cn', '简体中文'],
  ['zh-tw', '繁體中文'],
  ['yue', '粤语'],
  ['wyw', '古文'],
  ['ja', '日本語'],
  ['ko', '한국어'],
  ['fr', 'Français'],
  ['de', 'Deutsch'],
  ['es', 'Español'],
  ['it', 'Italiano'],
  ['ru', 'Русский'],
  ['pt', 'Português'],
  ['nl', 'Nederlands'],
  ['pl', 'Polski'],
  ['ar', 'العربية'],
  ['af', 'Afrikaans'],
  ['am', 'አማርኛ'],
  ['az', 'Azərbaycan'],
  ['be', 'Беларуская'],
  ['bg', 'Български'],
  ['bn', 'বাংলা'],
  ['bs', 'Bosanski'],
  ['ca', 'Català'],
  ['ceb', 'Cebuano'],
  ['co', 'Corsu'],
  ['cs', 'Čeština'],
  ['cy', 'Cymraeg'],
  ['da', 'Dansk'],
  ['el', 'Ελληνικά'],
  ['eo', 'Esperanto'],
  ['et', 'Eesti'],
  ['eu', 'Euskara'],
  ['fa', 'فارسی'],
  ['fi', 'Suomi'],
  ['fj', 'Fijian'],
  ['fy', 'Frysk'],
  ['ga', 'Gaeilge'],
  ['gd', 'Gàidhlig'],
  ['gl', 'Galego'],
  ['gu', 'ગુજરાતી'],
  ['ha', 'Hausa'],
  ['haw', 'Hawaiʻi'],
  ['he', 'עברית'],
  ['hi', 'हिन्दी'],
  ['hmn', 'Hmong'],
  ['hr', 'Hrvatski'],
  ['ht', 'Kreyòl Ayisyen'],
  ['hu', 'Magyar'],
  ['hy', 'Հայերեն'],
  ['id', 'Bahasa Indonesia'],
  ['ig', 'Igbo'],
  ['is', 'Íslenska'],
  ['jw', 'Jawa'],
  ['ka', 'ქართული'],
  ['kk', 'Қазақ'],
  ['mn', 'Монгол хэл'],
  ['tr', 'Türkçe'],
  ['ug', 'ئۇيغۇر تىلى'],
  ['uk', 'Українська'],
  ['ur', 'اردو'],
  ['vi', 'Tiếng Việt'],
]

export const Language = {
  getLanguages(type: 'CODE' | 'TEXT' = 'TEXT') {
    if (type === 'CODE') {
      return codeLanguages
    }
    return textLanguages
  },
}
