export const LANG_SELECT_WIDTH = 90

export const supportLanguages: [string, string][] = [
  ['Pascal', 'Pascal'],
  ['JavaScript', 'JavaScript'],
  ['TypeScript', 'TypeScript'],
  ['Python', 'Python'],
  ['TSX', 'TSX'],
  ['JSX', 'JSX'],
  ['Vue', 'Vue'],
  ['Go', 'Go'],
  ['C', 'C'],
  ['C++', 'C++'],
  ['Java', 'Java'],
  ['C#', 'C#'],
  ['Visual Basic .NET', 'Visual Basic .NET'],
  ['SQL', 'SQL'],
  ['Assembly Language', 'Assembly Language'],
  ['PHP', 'PHP'],
  ['Ruby', 'Ruby'],
  ['Swift', 'Swift'],
  ['SwiftUI', 'SwiftUI'],
  ['Kotlin', 'Kotlin'],
  ['R', 'R'],
  ['Objective-C', 'Objective-C'],
  ['Perl', 'Perl'],
  ['SAS', 'SAS'],
  ['Scala', 'Scala'],
  ['Dart', 'Dart'],
  ['Rust', 'Rust'],
  ['Haskell', 'Haskell'],
  ['Lua', 'Lua'],
  ['Groovy', 'Groovy'],
  ['Elixir', 'Elixir'],
  ['Clojure', 'Clojure'],
  ['Lisp', 'Lisp'],
  ['Julia', 'Julia'],
  ['Matlab', 'Matlab'],
  ['Fortran', 'Fortran'],
  ['COBOL', 'COBOL'],
  ['Bash', 'Bash'],
  ['Powershell', 'Powershell'],
  ['PL/SQL', 'PL/SQL'],
  ['CSS', 'CSS'],
  ['Racket', 'Racket'],
  ['HTML', 'HTML'],
  ['NoSQL', 'NoSQL'],
  ['Natural Language', 'Natural Language'],
  ['CoffeeScript', 'CoffeeScript'],
]

export const langMap: Map<string, string> = new Map(supportLanguages)

export const langMapReverse = new Map(
  supportLanguages.map(([standardLang, lang]) => [lang, standardLang]),
)
